MvcCachingData/Controllers/AggregateController.cs
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Mvc;
using MvcState.Infrastructure;

namespace MvcState.Controllers
{
    public class AggregateController : Controller
    {
        public ActionResult Index()
        {
            SelfExpiringData<long?> seData =
                (SelfExpiringData<long?>) HttpContext.Cache["pageLength"];
            return View(seData == null ? null : seData.Value);
        }

        [HttpPost]
        public async Task<ActionResult> PopulateCache()
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");
            long? data = result.Content.Headers.ContentLength;

            SelfExpiringData<long?> seData = new SelfExpiringData<long?>(data, 3);
            CacheDependency fileDep = new CacheDependency(Request.MapPath("~/data.txt"));
            AggregateCacheDependency aggDep = new AggregateCacheDependency();
            aggDep.Add(seData, fileDep);
            HttpContext.Cache.Insert("pageLength", seData, aggDep);

            return RedirectToAction("Index");
        }
    }
}

MvcCachingData/Views/Aggregate/Index.cshtml
@using System.Web.Mvc.Html
@model long?

@{
    Layout = "../Shared/_Layout.cshtml";
}

<div class="alert alert-info">
    @if (Model.HasValue)
    {
        @: Cached Data: @Model bytes
    }
    else
    {
        @: No Cached Data
    }
</div>

@using (Html.BeginForm("PopulateCache", "Aggregate"))
{
    <button class="btn btn-primary">Populate Cache</button>
}