MvcCachingData/Controllers/AnotherCachedController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Mvc;

namespace MvcState.Controllers
{
    public class AnotherCachedController : Controller
    {
        public ActionResult Index()
        {
            return View((long?)HttpContext.Cache["pageLength"]);
        }

        [HttpPost]
        public async Task<ActionResult> PopulateCache()
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");

            long? data = result.Content.Headers.ContentLength;
            CacheDependency dependency = new CacheDependency(Request.MapPath("~/data.txt"));
            HttpContext.Cache.Insert("pageLength", data, dependency);

            DateTime dt = DateTime.Now;
            CacheDependency timeStampDependency = new CacheDependency(null, new string[] { "pageLength" });
            HttpContext.Cache.Insert("pageTimeStamp", dt, timeStampDependency);

            return RedirectToAction("Index");
        }
    }
}

MvcCachingData/Controllers/BasicCachingController.cs
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MvcState.Controllers
{
    public class BasicCachingController : Controller
    {
        public ActionResult Index()
        {
            return View((long?)HttpContext.Cache["pageLength"]);
        }

        [HttpPost]
        public async Task<ActionResult> PopulateCache() 
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");
            HttpContext.Cache["pageLength"] = result.Content.Headers.ContentLength;
            return RedirectToAction("Index");
        }
    }
}

MvcCachingData/Controllers/NoAbsoluteCacheController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Mvc;

namespace MvcState.Controllers
{
    public class NoAbsoluteCacheController : Controller
    {
        public ActionResult Index()
        {
            return View((long?)HttpContext.Cache["pageLength"]);
        }

        [HttpPost]
        public async Task<ActionResult> PopulateCache()
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");
            long? data = result.Content.Headers.ContentLength;
            TimeSpan idleDuration = new TimeSpan(0, 0, 30);
            HttpContext.Cache.Insert("pageLength", data, null, Cache.NoAbsoluteExpiration, idleDuration);
            return RedirectToAction("Index");
        }
    }
}

MvcCachingData/Controllers/NoSlidingCacheController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Mvc;

namespace MvcState.Controllers
{
    public class NoSlidingCacheController : Controller
    {
        public ActionResult Index()
        {
            return View((long?)HttpContext.Cache["pageLength"]);
        }

        [HttpPost]
        public async Task<ActionResult> PopulateCache()
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");
            long? data = result.Content.Headers.ContentLength;
            DateTime expiryTime = DateTime.Now.AddSeconds(30);
            HttpContext.Cache.Insert("pageLength", data, null, expiryTime, Cache.NoSlidingExpiration);
            return RedirectToAction("Index");
        }
    }
}

MvcCachingData/Views/Shared/Many.cshtml
@model Dictionary<string, string>

@{
    Layout = "_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">Configuration Data</div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
        </thead>
        <tbody>
            @foreach (string key in Model.Keys)
            {
                <tr>
                    <td>@key</td>
                    <td>@Model[key]</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MvcCachingData/Views/Shared/One.cshtml
@model String

@{
    Layout = "_Layout.cshtml";
}

<div class="alert alert-success">Value: @Model</div>

MvcCachingData/Views/Shared/_Layout.cshtml
@{
    var appName = "MvcState";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@appName</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink($"Sukhoi1: {appName}", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li>@Html.ActionLink("Home-One", "Index", "Home")</li>
                    <li>@Html.ActionLink("Home-Many", "Many", "Home")</li>-->
                    <li><a href="~/Glimpse.axd">Glimpse</a></li>
                    <li>@Html.ActionLink("Basic", "Index", "BasicCaching")</li>
                    <li>@Html.ActionLink("NoSlidingExpiration", "Index", "NoSlidingCache")</li>
                    <li>@Html.ActionLink("NoAbsoluteExpiration", "Index", "NoAbsoluteCache")</li>
                    <li>@Html.ActionLink("FileDependency", "Index", "FileDependency")</li>
                    <li>@Html.ActionLink("DependOnAnotherCachedItem", "Index", "AnotherCached")</li>
                    <li>@Html.ActionLink("CustomDependency", "Index", "CustomDependency")</li>
                    <li>@Html.ActionLink("Aggregate", "Index", "Aggregate")</li>
                    <li>@Html.ActionLink("NotificationsAfterCacheEjection", "Index", "NotificationsAfter")</li>
                    <li>@Html.ActionLink("NotificationBeforeCacheEjection", "Index", "NotificationBeforeEjection")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year &copy; @appName</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>